### ISSUE TITLE
CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by HandsomeDevilv112** [deepsound-project/samplernn-pytorch#16]
I can get train.py to run if I don't use cuda. I'm using pytorch docker container, with nvidia-docker. 
nvcc-V reads "Cuda compilation tools, release 9.0, V9.0.176" 
nvidia-smi says "Driver Version: 384.111". 
While in python, running print(torch.backends.cudnn.is_acceptable(torch.cuda.FloatTensor(1)) and print(torch.backends.cudnn.version())  read "yes" and "7101"
I'm using python 3.6.4

My command line is:
root@6b27a1f07b65:~/samplernn-pytorch# python train.py --exp TEST --frame_sizes 16 4 --n_rnn 2 --dataset mega 

The process fails and produces:
Traceback (most recent call last):
  File "train.py", line 360, in <module>
    main(**vars(parser.parse_args()))
  File "train.py", line 184, in main
    model = model.cuda()
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 230, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 152, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 152, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 152, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 100, in _apply
    self.flatten_parameters()
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 93, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: CUDNN_STATUS_NOT_INITIALIZED

Any help would be appreciated.

**Comment by HandsomeDevilv112** [comment]
Updating cudnn did the trick. I'm still kinda baffled why the pytorch docker (for using pytorch) isn't set up to work off the shelf, but I've got working now. 
Closing.
